from endellion import EndellionBacktest
bt = EndellionBacktest(entry_mode="pullback")
bt.run()
m = bt.compute_metrics()
print("\n" + "="*62)
print("  PULLBACK-ONLY ENTRY (Original Spec)")
print("="*62)
print(f"  Total Trades:       {m['trades']}")
print(f"  Winning Trades:     {m['wins']}")
print(f"  Losing Trades:      {m['losses']}")
print(f"  Win Rate:           {m['win_rate']:.1f}%")
print(f"  Total PnL (10x):    {m['total_pnl']:+.1f}%")
print(f"  Profit Factor:      {m['profit_factor']:.2f}")
print(f"  Avg PnL/Trade:      {m['avg_pnl']:+.2f}%")
print(f"  Avg Win:            {m['avg_win']:+.2f}%")
print(f"  Avg Loss:           {m['avg_loss']:+.2f}%")
print(f"  Max Win:            {m['max_win']:+.2f}%")
print(f"  Max Loss:           {m['max_loss']:+.2f}%")
print()
print("  Per-Symbol:")
for sym, sd in m.get("by_symbol", {}).items():
    print(f"    {sym}: {sd['trades']} trades, {sd['pnl']:+.1f}% PnL, {sd['win_rate']:.1f}% WR")
print("="*62)
